### ISSUE TITLE
Lighthouse failure

### ISSUE THREAD

**Issue by hallmatt** [joytocode/lighthouse-lambda#11]
I'm getting some strange errors with various URLs (CNN, ESPN), but seems to work fine with version 1.1.3. Could this be related to the Chrome update? 

#1

`docker run --rm -v "$PWD":/var/task lambci/lambda:nodejs8.10 test.handler
START RequestId: f0cbe9ae-a354-191c-f278-947984547e3f Version: $LATEST
Thu, 31 May 2018 14:53:19 GMT status Initializing…
Thu, 31 May 2018 14:53:20 GMT status Loading page & waiting for onload URL, Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical, RobotsTxt, Fonts
Thu, 31 May 2018 14:54:05 GMT Driver:warn Timed out waiting for page load. Moving on...
Thu, 31 May 2018 14:54:05 GMT statusEnd Loading page & waiting for onload
Thu, 31 May 2018 14:54:05 GMT status Retrieving trace
Thu, 31 May 2018 14:54:05 GMT status Disconnecting from browser...
2018-05-31T14:54:05.136Z	f0cbe9ae-a354-191c-f278-947984547e3f	{"errorMessage":"not opened","errorType":"Error","stackTrace":["WebSocket.send (/var/task/node_modules/ws/lib/WebSocket.js:344:18)","CriConnection.sendRawMessage (/var/task/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:157:14)","CriConnection.sendCommand (/var/task/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:55:10)","Driver.sendCommand (/var/task/node_modules/lighthouse/lighthouse-core/gather/driver.js:206:29)","Promise (/var/task/node_modules/lighthouse/lighthouse-core/gather/driver.js:872:19)","new Promise (<anonymous>)","Driver.endTrace (/var/task/node_modules/lighthouse/lighthouse-core/gather/driver.js:864:12)","pass.then._ (/var/task/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:280:23)","<anonymous>"]}
2018-05-31T14:54:05.137Z	f0cbe9ae-a354-191c-f278-947984547e3f	Error: connect ECONNREFUSED 127.0.0.1:34279
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)`

#2 
`docker run --rm -v "$PWD":/var/task lambci/lambda:nodejs8.10 test.handler
START RequestId: 46956cd0-3b8a-1bda-6941-8c9ad77bb8e1 Version: $LATEST
Thu, 31 May 2018 14:59:39 GMT status Initializing…
Thu, 31 May 2018 14:59:39 GMT status Loading page & waiting for onload URL, Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical, RobotsTxt, Fonts
Thu, 31 May 2018 14:59:45 GMT statusEnd Loading page & waiting for onload
Thu, 31 May 2018 14:59:45 GMT status Retrieving trace
Thu, 31 May 2018 14:59:45 GMT status Retrieving devtoolsLog and network records
Thu, 31 May 2018 14:59:45 GMT GatherRunner:error FAILED_DOCUMENT_REQUEST https://espn.com/
Thu, 31 May 2018 14:59:45 GMT status Retrieving: URL
Thu, 31 May 2018 14:59:45 GMT status Retrieving: Scripts
Thu, 31 May 2018 14:59:45 GMT status Retrieving: CSSUsage
Thu, 31 May 2018 14:59:45 GMT status Retrieving: Viewport
Thu, 31 May 2018 14:59:45 GMT status Retrieving: ViewportDimensions
Thu, 31 May 2018 14:59:45 GMT status Retrieving: ThemeColor
Thu, 31 May 2018 14:59:45 GMT status Retrieving: Manifest
Thu, 31 May 2018 14:59:45 GMT status Retrieving: RuntimeExceptions
Thu, 31 May 2018 14:59:45 GMT status Retrieving: ChromeConsoleMessages
Thu, 31 May 2018 14:59:45 GMT status Retrieving: ImageUsage
Thu, 31 May 2018 14:59:45 GMT status Retrieving: Accessibility
Thu, 31 May 2018 14:59:45 GMT status Retrieving: EventListeners
Thu, 31 May 2018 14:59:45 GMT status Retrieving: AnchorsWithNoRelNoopener
Thu, 31 May 2018 14:59:45 GMT status Retrieving: AppCacheManifest
Thu, 31 May 2018 14:59:45 GMT status Retrieving: DOMStats
Thu, 31 May 2018 14:59:45 GMT status Retrieving: JSLibraries
Thu, 31 May 2018 14:59:45 GMT status Retrieving: OptimizedImages
Thu, 31 May 2018 14:59:45 GMT status Retrieving: PasswordInputsWithPreventedPaste
Thu, 31 May 2018 14:59:45 GMT status Retrieving: ResponseCompression
Thu, 31 May 2018 14:59:45 GMT status Retrieving: TagsBlockingFirstPaint
Thu, 31 May 2018 14:59:45 GMT status Retrieving: WebSQL
Thu, 31 May 2018 14:59:45 GMT status Retrieving: MetaDescription
Thu, 31 May 2018 14:59:45 GMT status Retrieving: FontSize
Thu, 31 May 2018 14:59:45 GMT status Retrieving: CrawlableLinks
Thu, 31 May 2018 14:59:45 GMT status Retrieving: MetaRobots
Thu, 31 May 2018 14:59:45 GMT status Retrieving: Hreflang
Thu, 31 May 2018 14:59:45 GMT status Retrieving: EmbeddedContent
Thu, 31 May 2018 14:59:45 GMT status Retrieving: Canonical
Thu, 31 May 2018 14:59:45 GMT status Retrieving: RobotsTxt
Thu, 31 May 2018 14:59:45 GMT status Retrieving: Fonts
Thu, 31 May 2018 14:59:45 GMT status Loading page & waiting for onload ServiceWorker, Offline, StartUrl
Thu, 31 May 2018 14:59:45 GMT statusEnd Loading page & waiting for onload
Thu, 31 May 2018 14:59:45 GMT status Retrieving devtoolsLog and network records
Thu, 31 May 2018 14:59:45 GMT GatherRunner:error FAILED_DOCUMENT_REQUEST https://espn.com/
Thu, 31 May 2018 14:59:45 GMT status Retrieving: ServiceWorker
Thu, 31 May 2018 14:59:45 GMT status Retrieving: Offline
Thu, 31 May 2018 14:59:45 GMT status Retrieving: StartUrl
Thu, 31 May 2018 14:59:46 GMT status Loading page & waiting for onload HTTPRedirect, HTMLWithoutJavaScript
Thu, 31 May 2018 14:59:46 GMT statusEnd Loading page & waiting for onload
Thu, 31 May 2018 14:59:46 GMT status Retrieving devtoolsLog and network records
Thu, 31 May 2018 14:59:46 GMT status Retrieving: HTTPRedirect
Thu, 31 May 2018 14:59:46 GMT status Retrieving: HTMLWithoutJavaScript
Thu, 31 May 2018 14:59:46 GMT status Disconnecting from browser...
Thu, 31 May 2018 14:59:46 GMT status Disconnecting from browser...
Thu, 31 May 2018 14:59:46 GMT CriConnection:warn disconnect() was called without an established connection.
2018-05-31T14:59:46.436Z	46956cd0-3b8a-1bda-6941-8c9ad77bb8e1	{"errorMessage":"FAILED_DOCUMENT_REQUEST","errorType":"LHError","stackTrace":["Function.getPageLoadError (/var/task/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:163:21)","pass.then._ (/var/task/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:298:36)","<anonymous>","process._tickDomainCallback (internal/process/next_tick.js:228:7)"]}`

**Comment by nmchau** [comment]
We have tested both sites you mentioned (https://cnn.com/ and https://www.espn.com/) and there is no problem. You should check again the inputs. Note that, https://espn.com URL doesn't exist or redirect to www subdomain.
