### ISSUE TITLE
Possibility of screenshots as output?

### ISSUE THREAD

**Issue by mrjomp** [joytocode/lighthouse-lambda#2]
Hello,
Thanks a lot for making lighthouse work with lambda first of all!

I think it would be amazing to have screenshots of how the webpage looks by generating an image output of the website in different device sizes just as lighthouse does when generating the report in the chrome extension and export them to an S3 bucket.

**Comment by baocancode** [comment]
The json result of Lighthouse already has those screenshots under the audit `screenshot-thumbnails`. However, the thumbnails are not high quality.
