### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:40481

### ISSUE THREAD

**Issue by yarikbratashchuk** [joytocode/lighthouse-lambda#30]
Hi!
I'm trying to test this stuff on a lambda function, and it works great! 
But for some reason, it returns an error when I'm trying to run it against https://common.com website, which is weird.
the error trace looks like this:
```
status Initializing…
status Loading page & waiting for onload
Driver:warn Timed out waiting for page load. Moving on...
status End Loading page & waiting for onload
status Retrieving trace
status Disconnecting from browser...
8ac8c570-9591-11e8-84e7-4d7a31e2572d	Error: connect ECONNREFUSED 127.0.0.1:40481 at Object._errnoException (util.js:1022:11) at _exceptionWithHostPort (util.js:1044:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
2018-08-01T13:49:03.112Z	8ac8c570-9591-11e8-84e7-4d7a31e2572d	Error: connect ECONNREFUSED 127.0.0.1:40481
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

do u have any ideas what is wrong with this?

thanks in advance

**Comment by baocancode** [comment]
Hi,

Looks like something wrong with our headless chrome binary. The same issue is reported at https://github.com/GoogleChrome/lighthouse/issues/5469. Therefore, we updated the code to use the binary of https://www.npmjs.com/package/@serverless-chrome/lambda. https://common.com/ runs ok now with lighthouse-lambda version 3.1 (or 2.1).

Can you try again?

**Comment by yarikbratashchuk** [comment]
Hey,

I confirm that version 3.1 indeed works!
I experienced another error with https://shopify.com, and now it's gone also.

Thanks a lot.

**Comment by baocancode** [comment]
No worries, thanks for testing it.
